language: objective-c
osx_image: xcode7.2

env:
  - SCHEME="BothamUIProject"
  - SCHEME="Example"   

before_install:
  - brew install swiftlint
  - gem install xcpretty
  - gem install cocoapods
  - gem install xcpretty-travis-formatter

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -f `xcpretty-travis-formatter`
