language: objective-c
osx_image: xcode7.2

before_install:
  - brew install swiftlint
  - gem install xcpretty
  - gem install cocoapods
  - gem install xcpretty-travis-formatter

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme 'BothamUIProject' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -f `xcpretty-travis-formatter`
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme 'Example' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -f `xcpretty-travis-formatter`
