language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: SCHEME="BothamUIProject"
      before_install:
        - gem install cocoapods --pre
        - brew install swiftlint
    - os: osx
      osx_image: xcode7.3
      env: SCHEME="Example"
      before_install:
        - gem install cocoapods --pre
        - brew install swiftlint
    - os: osx
      osx_image: xcode8
      env: SCHEME="BothamUIProject"
    - os: osx
      osx_image: xcode8
      env: SCHEME="Example"

install:
  - pod install

before_script:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -f `xcpretty-travis-formatter`
