language: objective-c
cache: cocoapods

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: SCHEME="BothamUIProject"
    - os: osx
      osx_image: xcode8
      env: SCHEME="Example"

before_script:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - pod repo update

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -f `xcpretty-travis-formatter`
