language: objective-c
osx_image: xcode7.1
cache: cocoapods

before_install:
  - brew install swiftlint
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme 'BothamUIProject' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
  - set -o pipefail && xcodebuild -workspace BothamUI.xcworkspace -scheme 'Example' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
